signTitle: [SignRanks]
changedGroup: "&2You have been &6promoted&2"
notEnoughMoney: "&2You do not have enough &6money &2to continue."
failedToChangePermission: "&2There was an unknown problem trying to &6promote &2you, sorry!"