name: SignRanks
version: 1.0.0
author: bittiez
main: US.bittiez.SignRanks.main
permissions:
    SignRanks.use:
        description: Allows the use of a rank sign
        default: op
    SignRanks.create:
        description: Allows creating of rank signs
        default: op
    SignRanks.break:
        description: Allows breaking of SignRanks signs
        default: op
softdepent: [Vault]